// Question:
/*
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.


Example 1:

Input: 
N = 4
arr[] = {4, 8, 12, 16}
Output: 8
Explanation:
Pair (8,12) has the Maximum AND Value 8.
Example 2:

Input:
N = 4
arr[] = {4, 8, 16, 2}
Output: 0
Explanation: Maximum AND Value is 0.

Your Task: The task is to complete the function maxAND() which takes the array elements and N (size of the array) as input parameters and returns the maximum AND value generated by any pair in the array. 

Expected Time Complexity: O(N * log M), where M is the maximum element of the array.
Expected Auxiliary Space: O(1).

Constraints:
1 <= N <= 105
1 <= arr[i] <= 105
*/


// Code:

// { Driver Code Starts
//Initial Template for C++
#include<bits/stdc++.h>
using namespace std;


 // } Driver Code Ends


//User function Template for C++
 
// Function for finding maximum and value pair
int maxAND (int arr[], int n)
{  
    int res = 0; 
    int count;
    for(int j=31;j>=0;j--) {
        unsigned int p =res | (1<<j);
        count = 0;
        for(int i=0;i<n;i++) {
            
            if((arr[i]&p) == p) {
                count++;
            }
        }
        if(count >= 2) {
            res = res | (1<<j); 
        }
    }
    return res;
    
}

// { Driver Code Starts.
 
// Driver function
int main()
{
    int t;
    cin>>t;//testcases
    while(t--)
    {
        int n;
        cin>>n;//input n
        int arr[n+5],i;
        
        //inserting elements
        for(i=0;i<n;i++)
        cin>>arr[i];
        
        //calling maxAND() function
        cout <<  maxAND(arr,n)<<endl;
    }
    return 0;
}  // } Driver Code Ends